# Use an common-base-llvm base image
FROM kushagra711/common-base-llvm:latest

# Copy your source code to the container

COPY . /repl-dev
# Set the working directory
WORKDIR /repl-dev/all-targets/repl

# Create a repl-build directory
RUN mkdir -p repl-build

# Configure and repl-build your project

WORKDIR /repl-dev/all-targets/repl/repl-build
#RUN cmake -G Ninja -DTESTS_ENABLED=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fuse-ld=lld" ..
#RUN ninja
#CMD ["./FlowWing"]
