version: "3.8"

services:
  aot-compiler-dev:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.AOTCompilerDev
    volumes:
      - .:/aot-compiler-dev
  jit-compiler-test:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.JITCompilerTest
    volumes:
      - .:/jit-compiler-test
  jit-compiler-dev:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.JITCompilerDev
    volumes:
      - .:/jit-compiler-dev
  repl-test:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.ReplTest
    volumes:
      - .:/repl-test
  repl-dev:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.ReplDev
    volumes:
      - .:/repl-dev
