# Define a reusable extension field for common service configurations.
x-compiler-base: &compiler-base
  build:
    context: .
    dockerfile: ./docker/Dockerfile
  volumes:
    - .:/compiler-dev
  tty: true

services:
  # Base compiler service for development.
  build-aot:
    <<: *compiler-base
    build:
      context: .
      dockerfile: ./docker/Dockerfile # Be explicit
      target: build-aot # Specifies to build up to the 'compiler-dev' stage in the Dockerfile.
    command: make build-aot

  build-jit:
    <<: *compiler-base
    build:
      context: .
      dockerfile: ./docker/Dockerfile # Be explicit
      target: build-jit # Specifies to build up to the 'compiler-dev' stage in the Dockerfile.
    command: make build-jit
  # Service for running Ahead-of-Time (AOT) tests.
  test-aot:
    <<: *compiler-base
    build:
      context: .
      dockerfile: ./docker/Dockerfile # Be explicit
      target: test-aot # Specifies to build up to the 'test-aot' stage in the Dockerfile.
    command: make test-aot

  # Service for running Just-in-Time (JIT) tests.
  test-jit:
    <<: *compiler-base
    build:
      context: .
      dockerfile: ./docker/Dockerfile # Be explicit
      target: test-jit
    command: make test-jit

  # Base REPL service for development.
  repl-dev:
    <<: *compiler-base
    build:
      dockerfile: ./docker/Dockerfile.ReplDev # Specify a different Dockerfile if needed.

  # Service for running REPL tests.
  test-repl:
    <<: *compiler-base
    build:
      dockerfile: ./docker/Dockerfile.ReplTest
    command: make test-repl
