services:
  aot-compiler-dev:
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.AOTCompilerDev
    volumes:
      - ../:/aot-compiler-dev
  aot-compiler-test:
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.AOTCompilerTest
    volumes:
      - ../:/aot-compiler-test
  jit-compiler-test:
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.JITCompilerTest
    volumes:
      - ../:/jit-compiler-test
  jit-compiler-dev:
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.JITCompilerDev
    volumes:
      - ../:/jit-compiler-dev
  repl-test:
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.ReplTest
    volumes:
      - ../:/repl-test
  repl-dev:
    tty: true
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.ReplDev
    volumes:
      - ../:/repl-dev
