#include "ElangIRConstants.h"

namespace ELANG::EVALUATOR::CONSTANTS {
const std::string ELANG_CONTINUE_COUNT = "ELANG_CONTINUE_COUNT";
const std::string ELANG_BREAK_COUNT = "ELANG_BREAK_COUNT";
const std::string ELANG_GLOBAL_ZERO = "ELANG_GLOBAL_ZERO";

// For Error

const std::string ELANG_GLOBAL_ERROR = "ELANG_GLOBAL_ERROR_COUNT";

// NULL

const std::string ELANG_GLOBAL_NULL = "ELANG_GLOBAL_NULL";

// TRUE AND FALSE KEYWORDS
const std::string ELANG_GLOBAL_TRUE = "ELANG_GLOBAL_TRUE";
const std::string ELANG_GLOBAL_FALSE = "ELANG_GLOBAL_FALSE";

}; // namespace ELANG::EVALUATOR::CONSTANTS