# AOT Tests Workflow with Caching for Performance
name: AOT Tests

on: [pull_request]

jobs:
  aot_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install ccache on the runner
      - name: Install ccache
        run: sudo apt-get update && sudo apt-get install ccache -y

      # Cache the ccache directory
      # The key is based on the OS and the hash of your source files
      # so it's invalidated only when your code changes significantly.
      - name: Cache ccache
        id: ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/Dockerfile') }}-${{ hashFiles('**/*.cpp', '**/*.cxx', '**/*.c', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build and Run AOT tests with ccache
        # We now use a single `docker compose run` command.
        # This command mounts the ccache directory and sets the CCACHE_DIR environment variable
        # so the compiler inside the container can use the cache.
        run: docker compose run --rm test-aot
        env:
          CCACHE_DIR: /ccache
        volumes:
          - ~/.ccache:/ccache
