name: AOT Tests

on: [pull_request]

jobs:
  test: # The job is for testing, not just building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Use the latest version for security and features
        uses: actions/checkout@v4

      - name: Build the specific test service image
        # We use docker-compose build, which respects the 'target: test'
        # in your docker-compose.yml file. This is simpler and more consistent
        # than using docker/build-push-action for this use case.
        run: docker compose build test-aot

      - name: Run AOT tests
        # This command starts the container from the image we just built.
        # It runs `command: make test-aot`. If tests fail, this step fails.
        # --no-build ensures it uses the image from the previous step.
        run: docker compose up --no-build --exit-code-from test-aot test-aot
