# JIT Tests Workflow with Caching for Performance
name: JIT Tests

on: [pull_request]

jobs:
  aot_test:
    runs-on: ubuntu-latest # You can try 'ubuntu-22.04' for a slightly more recent base

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # New Step: Cache Docker layers
      # This step checks for an existing cache of Docker layers and restores it.
      # If a cache is not found, it creates a new one after the build step.
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.docker/test-jit/
          # The paths are updated to reflect the docker-compose.yml in the root and Dockerfile in the docker folder
          key: ${{ runner.os }}-docker-${{ hashFiles('docker-compose.yml', 'docker/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build the specific test service image
        # Using a shared cache directory for the build to enable layer caching
        # No working directory is needed since the docker-compose file is in the root
        run: docker compose build test-jit --build-arg BUILDKIT_INLINE_CACHE=1

      - name: Run JIT tests
        # No working directory is needed here either
        run: docker compose up --no-build --exit-code-from test-jit test-jit
