name: Build and Test on All Platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ## ------------------ macOS Jobs ------------------ ##

  test_macos_arm64:
    name: Test on macOS (Apple Silicon)
    runs-on: macos-14 # ARM64 runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

      - name: Install Tools
        run: brew install ninja ccache automake autoconf libtool llvm@17

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            cmake/install
            .fw_dependencies
          key: ${{ runner.os }}-${{ runner.arch }}-deps-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}

      - name: Set Compiler Environment
        run: |
          echo "CC=$(brew --prefix llvm@17)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@17)/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix llvm@17)/lib -fuse-ld=lld" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix llvm@17)/include" >> $GITHUB_ENV

      - name: Install Dependencies
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: make deps-install-release

      - name: Build and Test
        run: make test-jit

  test_macos_x86_64:
    name: Test on macOS (x86_64)
    runs-on: macos-12 # x86_64 runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer

      - name: Install Tools
        run: brew install ninja ccache automake autoconf libtool llvm@17

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            cmake/install
            .fw_dependencies
          key: ${{ runner.os }}-${{ runner.arch }}-deps-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}

      - name: Set Compiler Environment
        run: |
          echo "CC=$(brew --prefix llvm@17)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@17)/bin/clang++" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix llvm@17)/lib -fuse-ld=lld" >> $GITHUB_ENV
          echo "CPPFLAGS=-I$(brew --prefix llvm@17)/include" >> $GITHUB_ENV

      - name: Install Dependencies
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: make deps-install-release

      - name: Build and Test
        run: make test-jit

  ## ------------------ Windows Job ------------------ ##

  test_windows_x86_64:
    name: Test on Windows (x86_64)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: choco install -y 7zip make

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            cmake/install
            .fw_dependencies
          key: ${{ runner.os }}-${{ runner.arch }}-deps-v2-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}

      - name: Install Dependencies
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: make deps-install-release

      - name: Build and Test
        # The environment is now correctly configured for your presets (MSVC + Ninja).
        run: make test-jit

  ## ------------------ Linux Job ------------------ ##
  test_linux_x86_64:
    name: Test on Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-17 ninja-build ccache automake autoconf libtool wget

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            cmake/install
            .fw_dependencies
          key: ${{ runner.os }}-${{ runner.arch }}-deps-${{ hashFiles('cmake/deps_builder/CMakeLists.txt') }}

      - name: Install Dependencies
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}
        run: make deps-install-release

      - name: Build and Test
        env:
          CC: clang-17
          CXX: clang++-17
        run: make test-jit
